#!/usr/bin/perl
use CGI;
my $q = new CGI;

my $data = CGI::param('POSTDATA');

if (($data ne ""))
{
	open (SEND, "|/usr/lib/sendmail -t");
	print SEND "From: mail\@mathias.re\n";
	print SEND "To: mail\@mathias.re\n";
	print SEND "Subject: CSP Report\n\n";
	print SEND "$data\n";
	close (SEND);
}

print $q->redirect('/');
